### ISSUE TITLE
[FEATURE] include assignments

### ISSUE THREAD

**Issue by ickooo** [almenscorner/IntuneCD#1]
Would be nice to include "Assignments" in the exported profiles. That way the exports can be used as documentation and overview to see where things are connected and what not. 
And if possible also to include it as DEV -> PROD that way it can be used to update assignments along side with configuration changes (scenario tenant to tenant migration).

**Comment by almenscorner** [comment]
Thank you for your feedback, I have started work on this feature

**Comment by almenscorner** [comment]
Hi,
A new version is now available on Test PyPi that includes assignments in backup, creation of non existing configurations and update of assignments on existing configurations. Please try this version. You can install it by running:
```python
pip install -i https://test.pypi.org/simple/ IntuneCD
```

Once I know everything works as expected I will create a PR to have the changes merged.

**Comment by ickooo** [comment]
Can confirm that after installing the test "IntuneCD" the backups now include Assignments = Groupname. Thank you!
