### ISSUE TITLE
[BUG] Permissions

### ISSUE THREAD

**Issue by Ma91Wa** [almenscorner/IntuneCD#102]
**Describe the bug**
I configured Intune-CD in November 2022. My azure app-registration has only "read-only" rights. But I only want to run a backup. I never want to give the permission to change something in Intune. 

App-Permissions:
- DeviceManagementApps.Read.All
- DeviceManagementConfiguration.Read.All
- DeviceManagementServiceConfig.Read.All
- Group.Read.All
- Policy.Read.All
- Policy.Read.ConditionalAccess
Backup was running good and without issues with the command:
I run IntuneCD-startbackup -m 1 -o yaml -p /home/intune-cd/backups/ -a /home/intune-cd/auth.json

now it does not work anymore.

Error:
`Traceback (most recent call last):
  File "/home/.local/bin/IntuneCD-startbackup", line 8, in <module>
    sys.exit(start())
  File "/home/.local/lib/python3.10/site-packages/IntuneCD/run_backup.py", line 275, in start
    run_backup(args.path, args.output, exclude, token)
  File "/home/.local/lib/python3.10/site-packages/IntuneCD/run_backup.py", line 166, in run_backup
    config_count += savebackup(path, output, exclude, token)
  File "/home/.local/lib/python3.10/site-packages/IntuneCD/backup_profiles.py", line 78, in savebackup
    oma_value = makeapirequest(
  File "/home/.local/lib/python3.10/site-packages/IntuneCD/graph_request.py", line 65, in makeapirequest
    raise Exception("Request failed with ", response.status_code, " - ", response.text)
Exception: ('Request failed with ', 403, ' - ', '{"error":{"code":"Forbidden","message":"{\\r\\n  \\"_version\\": 3,\\r\\n  \\"Message\\": \\"Application is not authorized to perform this operation. Application must have one of the following scopes: DeviceManagementConfiguration.ReadWrite.All - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 582c977c-d5a6-4e44-9662-d71207210082 - Url: https://fef.msub07.manage.microsoft.com/DeviceConfiguration_2303/StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations(\'3e5ea113-c420-468c-9484-1af5b8f05ce5\')/microsoft.management.services.api.getOmaSettingPlainTextValue(secretReferenceValueId=\'d9e8c134-50f1-4c93-9046-c96ab05dccbe_3e5ea113-c420-468c-9484-1af5b8f05ce5_d598bf61-aa91-4d6c-95b7-e50254d7ba0a\')?api-version=5022-09-24\\",\\r\\n  \\"CustomApiErrorPhrase\\": \\"\\",\\r\\n  \\"RetryAfter\\": null,\\r\\n  \\"ErrorSourceService\\": \\"\\",\\r\\n  \\"HttpHeaders\\": \\"{}\\"\\r\\n}","innerError":{"date":"2023-03-22T14:09:53","`

**To Reproduce**
I run IntuneCD-startbackup -m 1 -o yaml -p /home/intune-cd/backups/ -a /home/intune-cd/auth.json
My App-Registrations has the following permissions:

- DeviceManagementApps.Read.All
- DeviceManagementConfiguration.Read.All
- DeviceManagementServiceConfig.Read.All
- Group.Read.All
- Policy.Read.All
- Policy.Read.ConditionalAccess

**Expected behavior**
Backup working without issues with read-only permissions

**Run type (please complete the following information):**
 - Client local ubuntu and gitlab pipline
 - Version: 1.3.0

**Comment by almenscorner** [comment]
Hi,

This is a limitation in Graph, to use the "getOmaSettingPlainTextValue" endpoint you must have `DeviceManagementConfiguration.ReadWrite.All` on the app registration unfortunately.

**Comment by Ma91Wa** [comment]
This is working
