### ISSUE TITLE
[FEATURE] Decode JSON payloads for microsoft.graph.androidManagedStoreAppConfiguration

### ISSUE THREAD

**Issue by aaronparker** [almenscorner/IntuneCD#108]
The `payloadJson` property exported from `microsoft.graph.androidManagedStoreAppConfiguration` is encoded and therefore not human readable. Here's a sample from a generated document:

![image](https://github.com/almenscorner/IntuneCD/assets/8227455/cc1a4092-4c23-4b3f-ac51-419b4e622425)

**Describe the solution you'd like**
Decode the JSON from the base64 string returned from the Graph API.

**Comment by almenscorner** [comment]
Added to 1.4.6-beta.1, install the beta and run a new backup/document and let me know the results!

`pip install IntuneCD==1.4.6b1`

**Comment by almenscorner** [comment]
<img width="721" alt="Screenshot 2023-05-22 at 13 01 40" src="https://github.com/almenscorner/IntuneCD/assets/78877636/3b82ba56-a4ef-43e5-9c1a-d5b4b75d16f4">

**Comment by aaronparker** [comment]
Nice. Will check out my daily backup and report tomorrow.

**Comment by almenscorner** [comment]
Were you able to test this @aaronparker ? ☺️

**Comment by almenscorner** [comment]
You could just copy/clone the git repo on your machine locally and run IntuneCD from your terminal targeting that folder, or maybe I misunderstood? :)

**Comment by aaronparker** [comment]
Worked it out. Was using `pip3 install -e ./src/IntuneCD` instead of `pip3 install -e ./`

**Comment by aaronparker** [comment]
Looks good. 

A great byproduct of decoding the JSON payloads, is that PDF document don't get the `Click to expand` item that can't actually expand. This approach will make PDF versions of the as built more useful.

**Comment by almenscorner** [comment]
Awesome, thanks for verifying!

Yeah it's a much cleaner and more readable output ☺️
