### ISSUE TITLE
[FEATURE] Device categories

### ISSUE THREAD

**Issue by aaronparker** [almenscorner/IntuneCD#115]
**Is your feature request related to a problem? Please describe.**
Add backup/export of [device categories](https://learn.microsoft.com/en-us/mem/intune/enrollment/device-group-mapping).

**Describe the solution you'd like**
Ensure device categories are exported (and perhaps imported), so they can be added to import/export or as-built reports.

**Describe alternatives you've considered**
None

**Additional context**
Device categories requires the beta API, so it would be unsupported by MS. https://learn.microsoft.com/en-us/graph/api/resources/intune-shared-devicecategory?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0

**Comment by almenscorner** [comment]
Support for Device Categories has been added in the latest beta :) `pip install IntuneCD==1.4.8b1`

#116
