### ISSUE TITLE
[FEATURE] Include Resource ID in backupped files 

### ISSUE THREAD

**Issue by ztrhgf** [almenscorner/IntuneCD#133]
**Is your feature request related to a problem? Please describe.**
I want to enrich IntuneCD backup pipeline with information about who made such change. For this to happen I need to know resource (policy, app, etc) ID so I can look it up in the Intune audit logs easily.

**Describe the solution you'd like**
To each item IntuneCD back up add ResourceID property. To json file content (but that would probably break when I later try to import it?) or to its name as an optional suffix so it can be parsed. In general, it might be better to use ID instead of resource name in json file names, so GIT can easily track renames?

**Comment by almenscorner** [comment]
what is the benefit of using the ID when the type of config that is backed up is already appended to the file name? using the Object ID as the name of the file can easily become confusing when trying to find a configuration and would mess a bit with the documentation, archiving and update functions

**Comment by ztrhgf** [comment]
As I said, if you want to find out who made such change in the Intune log, you need a resource ID, because name cannot be used for the search. And there is no easy way to search through all Intune policies, to find the ID via policy name (moreover the policy can be in theory deleted already, so I won't be able to find it anyway). 
Using a name is even more useless in situations where you are checking some old GIT commit where the policy had a different name than it has now because someone renamed it during the time.

I can also delete the policy, a month later create a new one with the same name and again. If I go back in time it can be confusing because it seems like it is the same policy, but it is not.

I understand that displayname is more user-friendly when working with these config files manually. But for a programmatic approach, IDs would be better.

I am aware that changing the logic of naming conventions is problematic, therefore I suggested the option to add a suffix.

Maybe one more argument. Don't you like the idea that your tool can backup also the information about who made the change in the commit? Think of git blame that would tell you, who made this stupid change :)

**Comment by almenscorner** [comment]
Alright, gotcha. I will add it to the list to look into for next sprint of IntuneCD, right now there's a lot happening for the front end :)

**Comment by ztrhgf** [comment]
Super cool. 

A similar project https://github.com/microsoft/EntraExporter also uses IDs for exporting JSON and no one is complaining :)

**Comment by almenscorner** [comment]
Not complaining, I just wanted to understand the use case :)

**Comment by almenscorner** [comment]
A new argument has been added to version 2.0.2-beta.1, `--append-id` which lets you append the ID of the configuration to the filename. Please test and let me know how it works.

You can install the beta by running,
`pip install IntuneCD==2.0.2b1`

**Comment by ztrhgf** [comment]
Great! I'll test it right now and let you now 👍

**Comment by ztrhgf** [comment]
Seems good! No errors and all json's have '_<guid>' suffix.
Not sure if it is intention, but assignment reports contains just name (without suffix).

Looking forward for official release :)

**Comment by almenscorner** [comment]
Cool! Yes that is intentional as the assignment report is using the display name of the config :)

**Comment by ztrhgf** [comment]
OK I've noticed one bug. 

For proactive remediations, GUID is not the last item in the JSON's name. As last, there is **_RemediationScript** or **_DetectionScript**.

example:
prod-backup/Proactive Remediations/Script Data/BIOS_SecureBoot_Is_Enabled_e1f04276-de86-49c3-8dbf-521c64e1d2f7_RemediationScript.ps1

This makes it a little harder to extract GUID from the file name, as one would expect it to be always the last element.

**Comment by ztrhgf** [comment]
And one other bug?

JSON for "Apple push notification" gets with every backup different GUID in file name.

**Comment by ztrhgf** [comment]
One other tip that would be extremely helpful for anybody who is using GIT for tracking changes. **Sort** assignments report. Otherwise, there are unnecessary changes to such file 
![image](https://github.com/almenscorner/IntuneCD/assets/2930419/bf4f4505-0e42-432c-945a-18d82c20252b)
where just the order of the assignments changes, not the actual data.

This makes real changes less discoverable.

**Comment by ztrhgf** [comment]
And another possible bug (maybe on the Intune side though). I've noticed that sometimes backup (of for example ESP profile) shows that the assignment of some profile was removed, but that's not true (I've checked Intune logs just to be sure no one else made such a change). 
![image](https://github.com/almenscorner/IntuneCD/assets/2930419/bf52f3b6-6214-48c0-82f6-78bf8747a27d)

Have you noticed something similar too?

**Comment by almenscorner** [comment]
I think for APNs, there is really no need to append an ID as you can only have one APNs configured anyway so I will remove it from that payload.

As for Proactive Remediation yes, the type of the script is appended after the ID. I will look into it. Same goes for ESP.

I have not noticed that in my env. I've had ESPs backed up since 2022 and they have never had their assignment information removed.

**Comment by almenscorner** [comment]
Actually, the part after the GUID on the ESP is part of the actual ID for the configuration so that should stay as is in the filename.

**Comment by ztrhgf** [comment]
> Actually, the part after the GUID on the ESP is part of the actual ID for the configuration so that should stay as is in the filename.

Wow, you are right. Thats mess :D

Moreover, ESP changes aren't logged in Intune audit log at all...great

**Comment by ztrhgf** [comment]
Another missing GUID:

- Device Configurations\mobileconfig\WindowsDefenderATPOnboarding.xml
- Device Configurations\mobileconfig\notif.mobileconfig
- Device Management Settings\settings.json
- Scripts\Shell\Script Data\install_rosetta_arm64.sh
- Scripts\Powershell\Script Data\Invoke_WindowsUpdate.ps1
- Managed Google Play\contoso@gmail.com_androidManagedStoreAccountEnterpriseSettings.json

**Comment by almenscorner** [comment]
For Script Datas, mobileconfigs and Managed G Play I am not convinced the ID is needed in the filename. For script data and mobileconfig you have the ID of the parent config which is the actual object in Intune and should suffice.

Managed G Play is like APNs, you can only have one either way.

**Comment by ztrhgf** [comment]
For scripts it is a bit more complicated to find the ID from the "parent", but I suppose I can live with that.

But how am I supposed to know which "parent" policy belongs to which mobileconfig file? I honestly don't know :)

According to the managed g play and APNs. Without ID it is not possible to find related audit logs, no matter if there can be only one policy or not :)

**Comment by almenscorner** [comment]
So here is how I look at it.

Mobileconfig and script configurations have a base64 encoded payload which is the exported script and .mobileconfig. if any of these configurations changes, the base64 content in the backup will change and the exported file can be identified by the `payloadFileName` and `fileName` in the parent config. The audit logs in Intune will show the change of the parent config which is what you can extract the ID from in the backup.

Example custom macOS config file,

```json
{
     "@odata.type": "#microsoft.graph.macOSCustomConfiguration",
     "roleScopeTagIds": [
          "0"
     ],
     "deviceManagementApplicabilityRuleOsEdition": null,
     "deviceManagementApplicabilityRuleOsVersion": null,
     "deviceManagementApplicabilityRuleDeviceMode": null,
     "description": null,
     "displayName": "macOS - Custom - Privileges",
     "payloadName": "Privileges",
     **"payloadFileName": "privileges.mobileconfig",**
     "payload": "BASE64CONTENT",
     "deploymentChannel": "deviceChannel"
}
```

Whenever a change is made to Managed G Play, the activity will be `Patch AndroidForWorkSettings`, they category `Enrollment` and you know which configuration this is for as there can only be one

**Comment by ztrhgf** [comment]
I am sorry, but you are making this harder than it has to be :(

Imagine this (very real world) situation. The PowerShell script is deleted in the Intune. The backup is being run and detects such change. So I need to find the deleted script ID to be able to find the author of this change, but there is no JSON file in the repository to search for the ID (because it was deleted). If the ID is in the name, I can easily extract it, thanks to git ls-files.

This problem applies to all "child" files without ID in their name.

BTW, for scripts, this is inconsistent at the same time. Because Remediation scripts have "parent" JSON file with ID, but also "child" ps1 files have ID in the name. Shell and PowerShell scripts have IDs only in "parent" JSON.

Thank you in advance.

**Comment by ztrhgf** [comment]
And one even more serious problem I've encountered. For some policies it is super hard to understand what the ID is, because the file name contains several underscores. Good example is app protection policy.

Original name of the policy:
**Lvl 1 Data Protection policy (Android)**

JSON name:
prod-backup/App Protection/**Lvl 1 Data Protection policy (Android)_unspecified_T_41f4a526-a96c-45c0-ad89-31457bf2f7a5.json**

Policy ID:
**T_41f4a526-a96c-45c0-ad89-31457bf2f7a5**

And I guess there will be a lot more of such idiotic IDs (who the hell in the Microsoft team thought, GUIDs are not enough?!)


Solution:
Use more unique delimiter, like several underscores in a row? Something like 'policyname___id'? At the same time, it has to be something that will probably not occur in policy name itself.

Thank you for considering this change. Its quite important 👍
