### ISSUE TITLE
[BUG] Inconsistent addition of the ID when --append-id is used

### ISSUE THREAD

**Issue by ztrhgf** [almenscorner/IntuneCD#136]
**Describe the bug**
Remediation scripts have "parent" JSON file with ID suffix, but also "child" ps1 files have ID in the name. Shell and PowerShell scripts have IDs only in "parent" JSON.

**Solution**
Add an ID suffix to all "child" files (in this case Shell/PowerShell script files) too.

**Additional context**
Right now the absence of the ID in the file names doesn't make sense (the user already **explicitly chose to add the ID suffix**) plus makes work with your otherwise great tool unnecessarily hard (when working with IDs).

For example, I need a modified policies ID so I can search the Intune audit log for the author of such change.

Now imagine this (very real world) situation. Some PowerShell script is deleted in the Intune. The backup is being run and detects such change. So I need to find the deleted script ID to be able to find the author of this change, but there is no "parent" JSON file in the repository to search for the ID (because it was deleted). If the ID is in the file name, I could easily extract it.

This problem applies to all "child" files without ID in their name.

Thank you in advance 👍

**Comment by almenscorner** [comment]
"The backup is being run and detects such change. So I need to find the deleted script ID to be able to find the author of this change, but there is no "parent" JSON file in the repository to search for the ID (because it was deleted). If the ID is in the file name, I could easily extract it."

The "parent" JSON is never deleted from the repo by running a backup. It might be moved to __archive__ but it is never removed. So, if someone removes the Powershell script configuration from Intune, you will still be able to find it in the repo.

**Comment by CoMMyCZ** [comment]
Having a similar problem, having ID everywhere would be the most beneficial.

**Comment by ztrhgf** [comment]
> "The backup is being run and detects such change. So I need to find the deleted script ID to be able to find the author of this change, but there is no "parent" JSON file in the repository to search for the ID (because it was deleted). If the ID is in the file name, I could easily extract it."
> 
> The "parent" JSON is never deleted from the repo by running a backup. It might be moved to **archive** but it is never removed. So, if someone removes the Powershell script configuration from Intune, you will still be able to find it in the repo.

Yes, I know I can extract it from the GIT history, but it would be A LOT easier, to just have the ID in the file name...

**Comment by almenscorner** [comment]
I might just be me not seeing what benefit adding ID to the script file name will bring. Nonetheless, it's added to v2.0.3-beta.1.

Test and report back!

**Comment by almenscorner** [comment]
Make sure you also the the update functionality with this, not just backup.

**Comment by ztrhgf** [comment]
> Make sure you also the update functionality with this, not just backup.

Not sure what you mean? I've noticed this beta use '__' as a separator. Is that what you mean?

**Comment by almenscorner** [comment]
`IntuneCD-startbackup` is one command, however, these changes also affect `IntuneCD-startupdate` where the tool updates and creates configurations in Intune because the filenames of the scripts changes.

**Comment by ztrhgf** [comment]
BUGs:

1. Separator is incorrectly placed for Compliance Policies/Policies

![image](https://github.com/almenscorner/IntuneCD/assets/2930419/f447cd23-3d85-4699-89ed-dfefc7b6ff1f)

2. For Windows apps there are three underscores instead of two 
![image](https://github.com/almenscorner/IntuneCD/assets/2930419/cb3b4adc-9f92-4605-847b-40ca290b1da9)

**Comment by almenscorner** [comment]
Compliance is an easy fix, what _should_ be included after the _win32_ is the product version so it should be "_win32_{PRODUCTID}__{ID}". Does that app not have a product id?

**Comment by ztrhgf** [comment]
> looking at it, I think you have left the "App Version" blank in the Intune console which is why nothing is added to the export

Exactly, I don't set version at all :)

**Comment by ztrhgf** [comment]
Let me know when the new beta is released to test it out. Thanks!

**Comment by almenscorner** [comment]
these two has been fixed in 2.0.3 beta2 which is uploading now.

**Comment by ztrhgf** [comment]
Seems good now 👍

**Comment by ztrhgf** [comment]
Looking forward to the official release 

Thanks a lot for your work 👍

**Comment by ztrhgf** [comment]
btw this is the reason I need to have an ID [https://doitpsway.com/how-to-easily-backup-your-intune-environment-using-intunecd-and-azure-devops-pipeline](https://doitpsway.com/how-to-easily-backup-your-intune-environment-using-intunecd-and-azure-devops-pipeline)
