### ISSUE TITLE
[BUG] Ran into issues with Graph request, waiting 10 seconds and trying again... followed by failed backup

### ISSUE THREAD

**Issue by ztrhgf** [almenscorner/IntuneCD#137]
**Describe the bug**
I am running IntuneCD in the pipeline (so the newest version) with following parameters:
IntuneCD-startbackup \
                --mode=1 \
                --output=json \
                --path="$(Build.SourcesDirectory)/$(BACKUP_FOLDER)" \
                --exclude CompliancePartner \
                --append-id
From time to time following error makes the backup fail "Ran into issues with Graph request, waiting 10 seconds and trying again". When a new run of the backup is invoked, it finishes without any problems.

**To Reproduce**
This happens randomly, but I guess a better graph api error handling needs to be done.

**Expected behavior**
No error at all :) Maybe a longer wait time before another request is sent?

**Screenshots**
![image](https://github.com/almenscorner/IntuneCD/assets/2930419/1c7bee4b-fe57-4510-9fd1-5e9ed80b1c61)

**Run type (please complete the following information):**
 - Mode: 1
 - Client Ubuntu Pipeline
 - Version newest (2.0.2)

**Comment by almenscorner** [comment]
Graph can throw all sorts of responses at random times which makes it fun to work with :)

What can be done for the `504` response is add additional retries, so leave the timer at 10 seconds but try the request 3 times and error out if the response is still `504`.
