### ISSUE TITLE
[FEATURE] --exclude option for lastAppSyncDateTime in androidManagedStoreAccountEnterpriseSettings

### ISSUE THREAD

**Issue by Wob76** [almenscorner/IntuneCD#168]
**Is your feature request related to a problem? Please describe.**
Thank you so much for the addition of '-e VPPusedLicenseCount' as it has really helped clean up my commits. 
I have one more request, under "Managed Google Play" folder we get *__androidManagedStoreAccountEnterpriseSettings.json as pulled from the [graph api](https://learn.microsoft.com/en-us/graph/api/resources/intune-androidforwork-androidmanagedstoreaccountenterprisesettings?view=graph-rest-beta)

As per the api the file includes lastAppSyncDateTime which changes on every run (as you would expect).

**Describe the solution you'd like**
It would be nice to exclude this to again clean up the commit history

**Describe alternatives you've considered**
I could post process the file and remove this line, but having it stopped at the source similar to other excludes would be ideal.

Example file contents
```
{
     "bindStatus": "boundAndValidated",
     "lastAppSyncDateTime": "2024-02-13T20:25:10.7712992Z",
     "lastAppSyncStatus": "success",
     "ownerUserPrincipalName": "username@email.com",
     "ownerOrganizationName": "MyOrg",
     "enrollmentTarget": "targetedAsEnrollmentRestrictions",
     "targetGroupIds": [],
     "deviceOwnerManagementEnabled": true,
     "androidDeviceOwnerFullyManagedEnrollmentEnabled": true,
     "managedGooglePlayInitialScopeTagIds": [
          "57"
     ]
}
```

**Comment by almenscorner** [comment]
Please create a separate feature request for this

**Comment by Skorfulose** [comment]
@Wob76 @almenscorner 
Does this work for you? I have added the --exclude GPlaySyncTime parameter to my backup pipeline, and it still includes the ever-updating lastAppSyncDateTime property.

Looking at the [code in src/IntuneCD/intunecdlib/IntuneCDBase.py (line 50)](https://github.com/almenscorner/IntuneCD/blob/bfe6bff41479911cb86523bcdd7b6ed636d09ac9/src/IntuneCD/intunecdlib/IntuneCDBase.py#L50), I believe it should be `lastAppSyncDateTime` instead of `lastSyncDateTime`?

**Comment by Wob76** [comment]
No, it looks like it doesn't work. I still have a post process in place removing this and some other unwanted timestamps and licence counts, so it isn't showing in my final git push and I hadn't gone back to test.

**Comment by almenscorner** [comment]
You are right it should be `lastAppSyncDateTime`, I've corrected this in the latest beta, please test and verify the key is removed correctly: `pip3 install IntuneCD==2.3.2b1`
