### ISSUE TITLE
[BUG] resourceId is not added to scope tags json file name

### ISSUE THREAD

**Issue by ztrhgf** [almenscorner/IntuneCD#173]
**Describe the bug**
In version 2.1.0 backup of scopetags was added, but even though `--append-id` is used, tags are saved as  `'prod-backup/Scope Tags/Default__0.json'`

**Expected behavior**
Scope tag json file should contain its ID.

**Screenshots**

**Run type (please complete the following information):**
 - Mode: 1
 - Client Pipeline
 - Version 2.1.0

**Comment by almenscorner** [comment]
0, 1, 2 etc. is the ID of those payloads in Graph

**Comment by almenscorner** [comment]
For example:
![image](https://github.com/almenscorner/IntuneCD/assets/78877636/1f42f9ee-1f4e-4ad2-b82d-7ca7e7e7f156)

**Comment by almenscorner** [comment]
As I am using the ID provided by graph here for the Scope Tag in `--append-id` it is not a bug in IntuneCD

**Comment by ztrhgf** [comment]
You are correct. Thanks for clarification
