### ISSUE TITLE
[BUG] Scope Tag Assignments not always reported in the same order

### ISSUE THREAD

**Issue by Wob76** [almenscorner/IntuneCD#174]
**Describe the bug**
The order of the assignments in the Scope Tag files is not returned in a consistent order, this results in changes being logged even when no change exists.

I was undecided if I should call this a bug or a feature request, feel free to redefine.

I am not sure if this happens to other config files, but I noticed it last night in the scope tags.

**To Reproduce**
Run several backups and monitor for changes.

**Expected behavior**
We should not see changes when there are no real changes.

**Screenshots**
You can see below a remove and a add has been detected for the same groupname
![image](https://github.com/almenscorner/IntuneCD/assets/199897/575b6e1d-4486-470b-91e1-1414f73471ff)

I think if the groupname results were sorted before being stored this would solve this issue.

**Run type (please complete the following information):**
 - Mode: 1
 - Client: Pipeline
 - Version 2.1.2b3

**Comment by almenscorner** [comment]
Do you only see this behaviour in the beta or also in stable version? is there any failed batch retries occurring when this change happens in the ordering?

**Comment by Wob76** [comment]
Hi, at this stage I have only seen it on the Beta, and it hasn't been consistent, I'll tun some backups with the stable and report back.

**Comment by almenscorner** [comment]
I just want to make sure I am not doing any changes that in the end would mean new commits for hundreds of setups that are not seeing this behaviour today

**Comment by Wob76** [comment]
No problem at all, completely understand. I have been trying to debug more between other tasks, I have been able to get the same thing to happen in both Beta (pipeline) and Stable (local), but it is rare, less than 1 in 10 runs. 

I also can't be 100% sure it isn't being triggered by some change in our environment, there is not matching Intune audit event linked to a user, but as with a group name change this could be something happening outside Intune, eg in AAD. That said there is no change in the overall config, just some of the assignment groups move.

I have not seen it outside of the Scope Tags, and it is only impacting a small set, we have 158 scope tags and I have only seen < 5 in any one event.

I will try and fire up a new test pipeline running the stable release and have it trigger more frequently than the main one which is once a day, and see if I can narrow down the issue some more. In the mean time if you can think of anything you would like me to test I am more than happy to try.

**Comment by Wob76** [comment]
I will close this off for now, I have been running a stability test pipeline (every three hours) and this hasn't triggered for almost two weeks, I can't pin down the cause yet or say it isn't due to changes in the environment, I will re-open if I can pin this issue down or if it happens more frequently.
