### ISSUE TITLE
[BUG] Failed to create the "Windows Driver Update" Profile with Version 2.3.0b2

### ISSUE THREAD

**Issue by Edocsyl** [almenscorner/IntuneCD#184]
**Describe the bug**
Failed to create the "Windows Driver Update" Profile with Version 2.3.0b2

`Request failed with 400 - {"error":{"code":"BadRequest","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"Invalid property values - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: b9414aa3-89ff-4e0b-b7b9-xxxxxxxxxxx - Url: https://fef.amsua0102.manage.microsoft.com/Updates/SoftwareUpdateService/f42d0733-ffff-2597-0313-xxxxxxxxxxx/deviceManagement/windowsDriverUpdateProfiles?api-version=5023-07-14\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"date":"2024-03-20T09:08:47","request-id":"b9414aa3-89ff-4e0b-b7b9-xxxxxxxxxxx","client-request-id":"b9414aa3-89ff-4e0b-b7b9-xxxxxxxxxxx"}}}`

**To Reproduce**
Downgrade to version 2.2, the creation of the Profiles is working. 

**Run type (please complete the following information):**
 - Mode: 1
 - Client: local machine
 - Version: 2.3.0b2

**Comment by almenscorner** [comment]
Are you able to provide an example of the driver update profile backup it is trying to restore?

**Comment by almenscorner** [comment]
Think I found the issue, please try beta3, it is deploying now!

**Comment by Edocsyl** [comment]
Thanks, with beta3 it worked.
