### ISSUE TITLE
[BUG] Updating a macOS software update policy with group inclusions and exclusions

### ISSUE THREAD

**Issue by kdrwygvh** [almenscorner/IntuneCD#200]
**Describe the bug**
Hello. I have what might be a bug. An IntuneCD export that defines a macOS update policy with one included device group assignment and one excluded device group assignment is being used to update another tenant. When doing the update, the policy is created and the groups are created, but the assignment is not set on the policy itself.

**To Reproduce**
Steps to reproduce the behavior: Create a macOS software update policy with one included and one excluded device group

**Expected behavior**
The policy should be assigned and excluded as it was in the original backup

**Screenshots**

**Run type (please complete the following information):**
 - Mode: 1
 - Client local machine
 - Version 2.3.2

**Additional context**
When doing a report only run, I notice this:

Running in report mode, not making Graph POST request to https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/22a755c5-f827-48b8-b913-0ae745913184/assignments

But Microsoft's documentation for software update policies shows an example HTTP PATCH as

PATCH /deviceManagement/deviceConfigurations/{deviceConfigurationId}/groupAssignments/{deviceConfigurationGroupAssignmentId}/deviceConfiguration

per https://learn.microsoft.com/en-us/graph/api/intune-deviceconfig-macossoftwareupdateconfiguration-update?view=graph-rest-beta#http-request

Possible issue?

**Comment by almenscorner** [comment]
I think this issue was related to other device configuration assignment issues reported where the endpoint has changed. I was able to successfully deploy a macOS update policy with assignments using v2.3.3-beta1, try this version and report back if it works: `pip3 install IntuneCD==2.3.3b1`

**Comment by kdrwygvh** [comment]
2.3.3b1 resolves the issue.
