### ISSUE TITLE
[BUG] Script contents are overwritten with the contents of the first script in an update operation

### ISSUE THREAD

**Issue by kdrwygvh** [almenscorner/IntuneCD#211]
**Describe the bug**
When performing an update, scripts are being overwritten with the contents of one of the scripts from the backup

**To Reproduce**
1. Create two scripts in Intune, "Script 1" and "Script 2." The contents of the shell script can be a simple shebang and an echo line stating that the script is "script 1" and "script 2" respectively.
2. Perform an IntuneCD backup operation to download those scripts to disk
3. Perform an IntuneCD update operation

**Expected behavior**
The two scripts should still be in Intune and with the same script contents as they have on disk

**Screenshots**
<img width="1084" alt="Screenshot 2024-08-30 at 15 22 06" src="https://github.com/user-attachments/assets/3a0934b0-6dd0-4e81-bd8c-9a1582ba4ead">
<img width="1079" alt="Screenshot 2024-08-30 at 15 22 16" src="https://github.com/user-attachments/assets/623d2f3b-c136-4a9e-8d70-5c1f6d551d46">

**Run type (please complete the following information):**
 - Mode: 1
 - Client local machine
 - Version 2.3.4

**Additional context**

**Comment by almenscorner** [comment]
Able to replicate, will look into it

**Comment by almenscorner** [comment]
Please try the latest beta and check that scripts are not being updated with incorrect content, `pip3 install IntuneCD==2.3.5b1`

**Comment by kdrwygvh** [comment]
2.3.5b1 appears to resolve.
