### ISSUE TITLE
[FEATURE] Documentation separated into categories

### ISSUE THREAD

**Issue by MBVDK** [almenscorner/IntuneCD#27]
**Is your feature request related to a problem? Please describe.**
The current documentation markdown file can get heavy for the browser to view making it difficult to read without the browser crashing.

**Describe the solution you'd like**
Splitting the documentation into separate markdown files in the existing great folder structure. Ideally with a combined markdown file that has an index with references to the individual files.

**Comment by almenscorner** [comment]
Thank you for the feedback @MBVDK,

I have experienced this myself in larger setups, the idea you have is very interesting. How deep in the folder structure would you think is enough?

For example, under Management Intents we have a folder for all the different types of intents. Would it be OK to have one file for all management intents etc?

**Comment by almenscorner** [comment]
No worries, I will have a look at setting this up when time allows :)

**Comment by jlarmstrong** [comment]
I just want to second this; if you have a large deployment the output production single MD file can grow large enough that the PDF generation will fail.

**Comment by almenscorner** [comment]
I have a new version up on testpypi that includes a new parameter while running the documentation that lets you configure if you want to split the documentaion. Test this version by installing it using,

`pip install -i https://test.pypi.org/simple/ IntuneCD-beta`

You can then run documentation and split like this,

`intunecdbeta-startdocumentation -p /your/path -s Y`

An "index.md" file will be created in the path specified in `-p` that contains links to all MD files. This can also be combined with the new `-m` parameter that lets you specify the max length of the configurations to display.
