### ISSUE TITLE
[BUG] UnboundLocalError: local variable 'categories_responses' referenced before assignment

### ISSUE THREAD

**Issue by ricardocarrola** [almenscorner/IntuneCD#28]
**Bug**
When running an error was found : 

![image](https://user-images.githubusercontent.com/11631915/161930188-811e2615-57d8-4759-a2b9-3837d621ccc0.png)

**Original code file**

![image](https://user-images.githubusercontent.com/11631915/161930115-124c9822-ba14-4688-90e0-e5d83eb4f231.png)

categories_responses should be initialized prior to usage ( depends on the if )

**Comment by almenscorner** [comment]
Hi,

Thank for reporting, this looks like the same issue as in #26. Are you able to test with the steps I provided in that issue and report back if all works as expected?

**Comment by ricardocarrola** [comment]
hi there, I can confirm that using the Beta version solved the issue. Many thanks!
