### ISSUE TITLE
[BUG]: local variable 'platform' referenced before assignment

### ISSUE THREAD

**Issue by aaronparker** [almenscorner/IntuneCD#30]
**Describe the bug**
When running the following command in a tenant:

```bash
IntuneCD-startbackup -m 1 -o yaml -p ./prod-backup -a ./auth.json
```

This output is shown:

```bash
aaron@einstein pansw % IntuneCD-startbackup -m 1 -o yaml -p ./prod-backup -a ./auth.json
Backing up App Configuration: PDF Expert XML
Backing up App Configuration: PA Endpoint Defender IOS
Backing up App Protection: OneDrive mobile policy
Traceback (most recent call last):
  File "/opt/homebrew/bin/IntuneCD-startbackup", line 8, in <module>
    sys.exit(start())
  File "/opt/homebrew/lib/python3.9/site-packages/IntuneCD/run_backup.py", line 127, in start
    run_backup(opts.path,opts.output,token)
  File "/opt/homebrew/lib/python3.9/site-packages/IntuneCD/run_backup.py", line 66, in run_backup
    savebackup(path,output,token)
  File "/opt/homebrew/lib/python3.9/site-packages/IntuneCD/backup_AppProtection.py", line 59, in savebackup
    if platform == "mdmWindowsInformationProtectionPolicies":
UnboundLocalError: local variable 'platform' referenced before assignment
```

**To Reproduce**
There are no WIP policies in the target tenant, so the `mdmWindowsInformationProtectionPolicies` line may not be applicable. No App Protection policies are actually exported to disk. MAM policies in the tenant are:

![image](https://user-images.githubusercontent.com/8227455/162666398-96dcf7bb-2bd3-4dc0-b9d9-7a041b046eca.png)

**Expected behavior**
Backup should complete successfully

**Comment by almenscorner** [comment]
Hi,

I was not able to replicate this in version 1.0.8, can you verify you are running the latest version?

On another note, I have added a new Beta version that aims to fix the issue with backing up when there are no Management Intents configured. This Beta version also includes a parameter to skip assignments when backing up, requested in #29.

Please test this version by installing it with `pip install -i https://test.pypi.org/simple/ IntuneCD-beta` and running a backup with `IntuneCDBeta-startbackup`, to exlude assignments, all you have to do is add `-e assignments`.

Once I know all is looking good I will merge the changes to production.

**Comment by aaronparker** [comment]
Using `1.0.8`. I think the issue is something unique to this customer tenant - the `Global` listed under `Deployed` for the policy `OneDrive mobile policy` looks strange to me, so I'm thinking it could be the culprit. I will try replicate in my own tenant.

I'll test the beta version and see how it goes.

**Comment by aaronparker** [comment]
`IntuneCDBeta` was able to perform a backup.

**Comment by almenscorner** [comment]
Good to hear, then I will merge the changes tonight together with the ability to exclude assignments from backup. Thank you for reporting and testing!
