### ISSUE TITLE
[FEATURE] - Windows Device Configuration Export for ADMX templates

### ISSUE THREAD

**Issue by ickooo** [almenscorner/IntuneCD#33]
Would love to see exports available for windows device configurations with ADMX templates.

**Comment by almenscorner** [comment]
I have a new version up on testpypi that includes backup of Group Policy Configurations. You can install it by running,

`pip install -i https://test.pypi.org/simple/ IntuneCD-beta`

You can then run a backup like this,

`intunecdbeta-startbackup`

Test this version and verify that you can now see the configurations.
