### ISSUE TITLE
[BUG] UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff'

### ISSUE THREAD

**Issue by Kaze-tenshu** [almenscorner/IntuneCD#51]
When backing up my Intune settings I am seeing an error about Unicode encode errors

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\IntuneCD-startbackup.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\IntuneCD\run_backup.py", line 228, in start
    run_backup(args.path, args.output, exclude, token)
  File "c:\python39\lib\site-packages\IntuneCD\run_backup.py", line 184, in run_backup
    config_count += savebackup(path, output, exclude, token)
  File "c:\python39\lib\site-packages\IntuneCD\backup_powershellScripts.py", line 68, in savebackup
    f.write(decoded)
  File "c:\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to <undefined>

**Comment by almenscorner** [comment]
I managed to replicate your issue when running on a Windows host, the reason why it's failing is because your script contains a BOM character.

**Comment by basziee** [comment]
I have the same problem because a VPP app has the character \u03df in the name

**Comment by basziee** [comment]
Thank you, that helped. Now I have a new one
`first = '<br />&nbsp;&nbsp;&nbsp;&nbsp; - &nbsp;' + v[0]`
`TypeError: can only concatenate str (not "dict") to str`

I tried to change the + with a comma but no luck there

**Comment by almenscorner** [comment]
Looks like a side effect of the changes made to the documentation module today. I will have a look at it. Thanks for reporting :)

**Comment by basziee** [comment]
Hi @almenscorner 
Looks like It's working!

**Comment by almenscorner** [comment]
Nice, you should also see that the values in the tables are much better looking with indentation and new lines :)

**Comment by almenscorner** [comment]
To fix the encoding issue, set the following system variable in Windows: `PYTHONUTF8=1`
