### ISSUE TITLE
[BUG] TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by randomsunrize** [almenscorner/IntuneCD#52]
Hi I've successfully used pipelines for my dev tenant with the help from here: https://stealthpuppy.com/automate-intune-documentation-azure/
But I can't seem to get it working for my prd tenant, it's stuck on generating the markdown document.

- task: Bash@3
      displayName: Generate markdown document
      inputs:
        targetType: 'inline'
        script: |
INTRO="Endpoint Manager"
IntuneCD-startdocumentation \
              --path="$(Build.SourcesDirectory)/prod-backup" \
              --outpath="$(Build.SourcesDirectory)/prod-as-built.md" \
              --tenantname=$TENANT_NAME \
              --intro="$INTRO" \
              #--split=Y
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: true
      env:
        TENANT_NAME: $(TENANT_NAME)

Output:
Traceback (most recent call last):
  File "/home/vsts/.local/bin/IntuneCD-startdocumentation", line 8, in <module>
    sys.exit(start())
  File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/run_documentation.py", line 193, in start
    run_documentation(args.path, args.outpath, args.tenantname, args.jsondata, args.maxlength, args.split)
  File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/run_documentation.py", line 78, in run_documentation
    document_configs(f'{configpath}/Apple VPP Tokens', outpath, 'Apple VPP Tokens', maxlength, split)
  File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/documentation_functions.py", line 215, in document_configs
    md.write('## ' + repo_data['displayName'] + '\n')
TypeError: can only concatenate str (not "NoneType") to str
##[error]Bash exited with code '1'.
##[error]Bash wrote one or more lines to the standard error stream.
##[error]Traceback (most recent call last):

 - Mode: [1]
 - Client [Pipeline]

**Comment by almenscorner** [comment]
Hi!

Can you share the contents of the VPP configurations? it looks like you have a null value on the displayName for VPP

**Comment by randomsunrize** [comment]
Thanks very much :)
There happened to be a vpp without a token name somehow, either way the token was expired. The token was named "none" when it converted to json. 
![redact (3)](https://user-images.githubusercontent.com/82435612/185104361-093e01e6-6edd-4a8c-bd21-d75faad872ed.png)
![redact (4)](https://user-images.githubusercontent.com/82435612/185104399-c5350a8d-9461-4bca-9117-b0593163c43d.png)
