### ISSUE TITLE
[FEATURE] Sort alphabetically in the .md file

### ISSUE THREAD

**Issue by randomsunrize** [almenscorner/IntuneCD#53]
Is it possible if all the contents of everything (App Configuration, App Protection, Apple Push Notification etc.) were sorted alphabetically  in the .md file like they are when you back up everything to the folders in  json or yaml?

**Comment by almenscorner** [comment]
Should just be a matter of sorting the configuration files when documenting them. I'll look into it!

**Comment by randomsunrize** [comment]
thank you :)
