### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'pop'

### ISSUE THREAD

**Issue by aaronparker** [almenscorner/IntuneCD#62]
**Describe the bug**
Conditional Access backup produces `AttributeError: 'NoneType' object has no attribute 'pop'`. API permissions have been updated to include all required permissions.

**To Reproduce**
Backing up a policy with the name `Office 365 - E5; Unmanaged platforms; Browser; Use Conditional Access App Control`. My next test will be to re-name the policy to remove the `;` character.

**Expected behavior**
Backup should complete.

```log
Backing up Conditional Access policy: Office 365 - E5; Unmanaged platforms; Browser; Use Conditional Access App Control
Traceback (most recent call last):
  File "/home/runner/.local/bin/IntuneCD-startbackup", line 8, in <module>
    sys.exit(start())
  File "/home/runner/.local/lib/python3.8/site-packages/IntuneCD/run_backup.py", line 246, in start
    run_backup(args.path, args.output, exclude, token)
  File "/home/runner/.local/lib/python3.8/site-packages/IntuneCD/run_backup.py", line 210, in run_backup
    config_count += savebackup(path, output, token)
  File "/home/runner/.local/lib/python3.8/site-packages/IntuneCD/backup_conditionalAccess.py", line 36, in savebackup
    policy['grantControls'].pop('authenticationStrength@odata.context', None)
AttributeError: 'NoneType' object has no attribute 'pop'
Error: Process completed with exit code 1.
```

**Run type (please complete the following information):**
 - Mode: 0
 - Client: Pipeline
 - Version 1.2

**Comment by almenscorner** [comment]
Looks like it's failing because there's no 'grantControls' configured on the policy. I will try to replicate tomorrow and release a bug fix for that!

**Comment by aaronparker** [comment]
In this lab environment I have several CA policies that implement Use Conditional Access App Control with seperate policies for managing MFA. I'll update those Use Conditional Access App Control policies with MFA in the meantime and re-test.
