### ISSUE TITLE
[BUG] Able to backup Management Intents, but not update

### ISSUE THREAD

**Issue by Ozurian** [almenscorner/IntuneCD#70]
**Describe the bug**
The process errors out whenever we try to run an update with Management Intents present in the backup.

The error given is simply "TypeError: can only concatenate str (not "NoneType") to str":

Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\IntuneCD-startupdate.exe\__main__.py", line 7, in <module>
  File "C:\Python\lib\site-packages\IntuneCD\run_update.py", line 207, in start
    run_update(args.path, token, args.u, exclude)
  File "C:\Python\lib\site-packages\IntuneCD\run_update.py", line 152, in run_update
    diff_count += update(path, token, assignment)
  File "C:\Python\lib\site-packages\IntuneCD\update_managementIntents.py", line 39, in update
    intent_responses = batch_intents(intents, token)
  File "C:\Python\lib\site-packages\IntuneCD\graph_batch.py", line 154, in batch_intents
    categories_responses = batch_request(
  File "C:\Python\lib\site-packages\IntuneCD\graph_batch.py", line 39, in batch_request
    'url': url + id + extra_url
TypeError: can only concatenate str (not "NoneType") to str

**To Reproduce**
- Create some policies in one of the blades covered by intents, such as Bitlocker and the like.
- Backup the policy
- Try to import

**Expected behavior**
- For the policies to manage to update the target tenant

**Screenshots**

**Run type (please complete the following information):**
 - Mode: 1
 - Client Local Machine
 - Version 1.2.5

**Additional context**
An example policy I tested with is attached
[TEST-BITLOCKER-2.2022.12.json.zip](https://github.com/almenscorner/IntuneCD/files/10154665/TEST-BITLOCKER-2.2022.12.json.zip)

**Comment by almenscorner** [comment]
Hi,

I tried with the configuration you sent as an example and it was created as a new configuration just fine in my environment and I was able to update the configuration.

In what scenario do you get this error? i.e. is it when trying to deploy to a new env without any configs or updating the config in a current env where it exists?

**Comment by Ozurian** [comment]
I just double checked all the permissions now and also verified I was able to import back to the dev environment too, so that narrowed it down to simply this other test tenant.

I did find something really strange when digging further using the graph API, as in this test tenant I get back lots of response objects that are not visibile in the management portal at microsoft. And they all lack a proper value for template id so it makes sense with the none error:

Example:


id                   : 98b3d3c2-adc5-44bb-ac2f-9df8d3bd54b9
displayName          : My-Policy-Name-Here
description          : Application control
isAssigned           : False
lastModifiedDateTime : 15.08.2022 18:33:16
templateId           :
roleScopeTagIds      : {0, 1}

If entries without a template id could be ignored I wonder if this would most likely work in such cases too.

(I verified I could query out all these using the same application id and secret I am trying to use for the update)

**Comment by almenscorner** [comment]
I ran into that myself some time ago and did add a check for null template id here:

https://github.com/almenscorner/IntuneCD/blob/cb37cf7a54dcd9742de4d11a6b3ee93e127796e1/src/IntuneCD/graph_batch.py#L153

I'm trying to figure out a way I can replicate this and implement a fix for the scenario :)

**Comment by Ozurian** [comment]
Ahh, based on that line it seems like it only checks for the key to be present and not having any value so when I changed line 149 locally here to:

for key, val in list.items() if 'templateId' in key and val != None]

It actually worked and created the policy without issue this time!

**Comment by almenscorner** [comment]
Nice catch, I'll add that fix as part of some other updates due to be pushed tomorrow ☺️

**Comment by Ozurian** [comment]
Thanks for all the help in putting me on the right track here and making this wonderful project too! 😊

**Comment by almenscorner** [comment]
I deliberately forced a None value on the template Id but even then I don't get this error. Would really like to be able to replicate and narrow down what is happening

**Comment by Ozurian** [comment]
It is definitely a very strange error indeed, after trying and failing a bit more here I got it to work by changing line 160 as well to the following:

settings_ids = [val for list in categories_responses if intent['templateId'] != None and intent['templateId'] in list['@odata.context']

Not sure if that is the cleanest way to write this, but now it successfully both creates the item if missing and updated the setting just fine too. Tested editing it in the test environment and running a new update and it forced back the proper value from the backup as expected :)
