### ISSUE TITLE
[BUG] Restore fails with compliance policies that do not exist and contain scheduledActionConfigurations

### ISSUE THREAD

**Issue by Ozurian** [almenscorner/IntuneCD#76]
**Describe the bug**
When restoring compliance policies, it fails if the policy does not already exist and contains the properties for "scheduledActionConfigurations"

For testing attempted to create a policy with the same name I was trying to restore in the target environment and then it worked.
I noticed that there are some calls to "remove_keys" in the code path that is executed when the policy already exists, but this does not seem to be the case for the code path that has to create the policy when missing.

**To Reproduce**
Steps to reproduce the behaviour:
- Create a policy that contains compliance notification settings and back it up
- Attempt to restore the policy to an environment that does not contain a policy with the same name

**Expected behaviour**
For the policy to be created successfully

**Screenshots**

**Run type (please complete the following information):**
 - Mode: 1
 - Client: Local
 - Version: 1.2.8

**Additional context**

**Comment by almenscorner** [comment]
Hi @Ozurian,

Do you get any errors when it tries to create the policy? I just tried the reproduction steps you provided and the policy created without any issues. If the policy contains message templates however they are not added but the policy and scheduled actions were successfully added.

**Comment by Ozurian** [comment]
@almenscorner 

The error that occurs is this one:
![image](https://user-images.githubusercontent.com/4451996/207253515-37fb9c34-d3d3-4534-aa1d-a2c057ded091.png)

[iOS-Test-Compliance.zip](https://github.com/almenscorner/IntuneCD/files/10215521/iOS-Test-Compliance.zip)

**Comment by almenscorner** [comment]
Can you do a new backup of the policy? it looks like keys that should be removed from the policy is not removed from that JSON. I did a new export in JSON myself and keys like ID should not be there in the backup.

**Comment by Ozurian** [comment]
The backup itself gives no errors and generated the JSON file I attached, it never seems to give any hard errors on that step even though it ends up with these properties that should not be there

**Comment by almenscorner** [comment]
Very strange, I tried to get a JSON generated with they keys still there like you have in the attached example but I'm not able to replicate that. I tried in a pipeline in Azure DevOps, a macOS host and a Windows host but it exports without the keys like it should on all of them.

**Comment by Ozurian** [comment]
I think I see what is happening here now, since I have excluded assignments from backup the whole section that removes the keys is skipped due to the if check here:

https://github.com/almenscorner/IntuneCD/blob/eddb84a20111a23ef70e31adcb0754e526f8670b/src/IntuneCD/backup_compliance.py#L41

**Comment by almenscorner** [comment]
You are right, that is for sure a bug in the compliance backup module. I will push a patch for that today to get it sorted!

**Comment by Ozurian** [comment]
That sounds great, thanks!

**Comment by almenscorner** [comment]
Thank you for finding that one ☺️
