### ISSUE TITLE
IntuneCD Script backup BUG

### ISSUE THREAD

**Issue by Nikolara97** [almenscorner/IntuneCD#78]
Hi there,

Once I run tool locally with command: IntuneCD-startbackup -m 1 -o yaml -p /path/to/save/in -a /path/to/auth.json/
everything starts backing up from our Intune, but once it comes to script part of backup, we are getting this message:

<img width="945" alt="image" src="https://user-images.githubusercontent.com/121571467/209848024-15d151f8-3fc2-4fff-b9e5-66967812a055.png">

Can you please help?

**Comment by almenscorner** [comment]
Hi,

Try the solution provided here: https://github.com/almenscorner/IntuneCD/issues/51#issuecomment-1340959764

**Comment by almenscorner** [comment]
Hi,

Did the above solution work for you?

**Comment by Nikolara97** [comment]
Hi, yes it works in local now thanks so much. Is there any chance you can make some instructions/manual how to use it in AzureDevops. I am new to this and i am facing some hard time about this part. Once i try to run pipeline i am getting all kind of errors... I probably do something wrong with definition of variables, idk what to put for git user name/mail, etc... I think this manual would help me allot to understand concepts on AzureDevops and IntuneCD tool. Thanks ✌🏻
    On Thursday, January 5, 2023 at 02:49:22 PM GMT+1, Tobias Almén ***@***.***> wrote:  
 
 


Hi,

Did the above solution work for you?

**Comment by almenscorner** [comment]
@aaronparker wrote a great blog post on that which you can find here: https://stealthpuppy.com/automate-intune-documentation-azure/

Let me know if you need additional help!

**Comment by Nikolara97** [comment]
Thank you so much, I created everything from this link and it's working without issues. now I just want to configure one last pipeline for intunecd-startupdate. I saw your example, but I am not pretty sure can it work or is it working like I am thinking. If I am not wrong, if I clone whole backup in local and for example, I change just one configuration for something, push those updates back to AzureDevops and run your example pipeline for intune-startupdate will this push those changes to Intune?

<img width="323" alt="image" src="https://user-images.githubusercontent.com/121571467/211520409-d0e9d7a6-0867-4370-90dd-516589fc3d70.png">

I am curious how pipeline knows from where to push those changes... Or if you have some sample pipeline that can do what I have mention above would be really awesome.

Thanks

**Comment by almenscorner** [comment]
What you can do is to add this to the pipeline at the top,

```yaml
trigger:
 branches:
  include:
    - main
```

This will ensure that whenever a push is made to the main branch, the pipeline will run.

So, if you clone the Git repo locally, change a value, commit it and push to main, the pipeline will run and update the configuration in Intune with the new value.

What happens when `IntuneCD-startupdate` runs is that it will compare the settings you have in the Intune environment specified in the ENV vars for the pipeline to what you have in the Git repo. If the configuration in Intune differs from what is in the repo, IntuneCD will update that configuration with the new setting.

This way, the source is always the Git repo, the configurations that are there is what is in production.

**Comment by Nikolara97** [comment]
Thanks, I manage to configure it. It's working like a charm :)
    On Tuesday, January 10, 2023 at 01:17:59 PM GMT+1, Tobias Almén ***@***.***> wrote:  
 
 


What you can do is to add this to the pipeline at the top,
trigger:
 branches:
  include:
    - main
This will ensure that whenever a push is made to the main branch, the pipeline will run.

So, if you clone the Git repo locally, change a value, commit it and push to main, the pipeline will run and update the configuration in Intune with the new value.

What happens when IntuneCD-startupdate runs is that it will compare the settings you have in the Intune environment specified in the ENV vars for the pipeline to what you have in the Git repo. If the configuration in Intune differs from what is in the repo, IntuneCD will update that configuration with the new setting.

This way, the source is always the Git repo, the configurations that are there is what is in production.

**Comment by almenscorner** [comment]
Good to hear :)

I will go ahead and close this issue. If you have any additional questions or problem, open a new issue or create a new discussion!
