### ISSUE TITLE
[FEATURE] Support for other auth methods

### ISSUE THREAD

**Issue by kenchan0130** [almenscorner/IntuneCD#84]
**Is your feature request related to a problem? Please describe.**

InutneCD only supports the client credential method (the client secret authentication）.
However, for local execution or for more secure secret management, another method is commonly used.

**Describe the solution you'd like**

I would like to see support for methods other than the client credential method (the client secret authentication）.

- Azure CLI authentication
- Client certificate authentication
- MSI authentication
- GitHub OIDC authentication

**Describe alternatives you've considered**

N/A

**Additional context**

The Graph API client used by [azuread provider](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs), which manages Azure AD with terraform, supports several auth methods.
https://github.com/manicminer/hamilton/blob/main/auth/auth.go#L23-L43

**Comment by almenscorner** [comment]
Hi,

I'm currently working on switching `ADAL` over to `MSAL` as adal is deprecated. By doing this you will be able to use a certificate to authenticate or interactive mode to sign in with your account when running IntuneCD.

Currently, the MSAL Python module does not support Managed Identities (MSI). See this link for reference: https://msal-python.readthedocs.io/en/latest/#msal.PublicClientApplication.params.azure_region

Would it be enough with these authentication options?:
- Client Credential
- Cert
- Interactive

Managed Identities would be added when support is added to the MSAL module.
