### ISSUE TITLE
Export definitions of Applications

### ISSUE THREAD

**Issue by joaocc** [almenscorner/IntuneCD#9]
Thanks for the amazing work!
Would it be possible to export the definitions of Applications (package IDs and such), even if they can't be imported?
Thanks

**Comment by almenscorner** [comment]
Hi Joao,

Thank you!

It's definitely possible to add this for the purpose of backup/documentation. I have a few things in mind to add that will be backup only
- Applications
- APNs
- Managed Google Play

Let me know if there are additional configurations you'd like to see supported by the tool. I will start planning the next update soon!
