### ISSUE TITLE
IntuneCD backup problem

### ISSUE THREAD

**Issue by Nikolara97** [almenscorner/IntuneCD#92]
Hi Almen,

I think IntuneCD backup feature are having some problem now and I can't sow why.

It's both if I run it from Azure Devops or Local pc. It's backing up some components and in the middle of backup it's just stops. This was working like charm 2 days ago. Can you check please?

Error is in pic below:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/121571467/219676188-d61628ae-0547-4cea-9e3c-2fe6af5263f0.png">

**Comment by almenscorner** [comment]
Hi,

Is it failing on the same policy every time or just a random one?

**Comment by Nikolara97** [comment]
Hi,
I have just check from my pipeline and it fails on different profiles...
    On Friday, February 17, 2023 at 03:10:35 PM GMT+1, Tobias Almén ***@***.***> wrote:  
 
 


Hi,

Is it failing on the same policy every time or just a random one?

**Comment by almenscorner** [comment]
I just setup a new pipeline and tried to three different environments and I'm not getting this error. I have seen this randomly happen when there is a problem with the Graph API however but usually self resolves on the next run.

**Comment by almenscorner** [comment]
@Nikolara97 are you running into this issue still?

**Comment by Nikolara97** [comment]
Hi,
Yesterday and today pipeline was running successfully like you mentioned it start working on its own, and it was failing like 2-3 days in row. Never mind it's working now, thanks. :)
    On Monday, February 20, 2023 at 09:38:18 AM GMT+1, Tobias Almén ***@***.***> wrote:  
 
 


@Nikolara97 are you running into this issue still?

**Comment by almenscorner** [comment]
Thanks for confirming. I will monitor for this in my pipelines as well, closing this issue for now!

**Comment by Nikolara97** [comment]
Sure,
Now it's happening for update pipeline as well... Your suggestion, just to give it couple of days as well?
    On Monday, February 20, 2023 at 09:55:45 AM GMT+1, Tobias Almén ***@***.***> wrote:  
 
 


Closed #92 as completed.
