### ISSUE TITLE
Update pipeline problems

### ISSUE THREAD

**Issue by Nikolara97** [almenscorner/IntuneCD#93]
Hi Almen,

Coupe days ago, I told you there was problem with backup pipeline and now I am facing it for update pipeline. But now configuration is always failing on same policy and it's working If I run it locally.  (This pipeline was working in past...)

Error code:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/121571467/220298230-72147b95-16d4-4239-bc1f-9b5110b45bb9.png">

Any suggestion? Will it start working like backup pipeline on it's own in couple of days?

**Comment by almenscorner** [comment]
Do I understand correctly you are not getting this error if you run the update towards the same environment locally?

**Comment by almenscorner** [comment]
Can you try to do a new backup of the Windows Enrollment profiles in the repo and run the update after that?

**Comment by Nikolara97** [comment]
Yeah, If I run it's locally on same env there is no any errors at all. Already tried that and it's not working.

**Comment by almenscorner** [comment]
Can you share the YAML of the pipeline used?

**Comment by Nikolara97** [comment]
Sure, here it is:

`trigger:
 branches:
  include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
  REPO_DIR: $(Build.SourcesDirectory)/git-backup-update-test

steps:

- checkout: self
  persistCredentials: true

- script: pip3 install IntuneCD
  displayName: Install IntuneCD

- script: IntuneCD-startupdate -m 1
  env:
    REPO_DIR: $(REPO_DIR)
    TENANT_NAME: $(TENANT_NAME)
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
  displayName: Run update`

**Comment by almenscorner** [comment]
Can you double check that there is no duplication of the enrollment profiles in the repo, for example the same config is saved in both YAML and JSON?

**Comment by almenscorner** [comment]
I'm really struggling to replicate this, especially since it is working from your machine locally. I cannot see that the fault would be in the tool in that case.

This is probably the last thing you want to do but can you try to create a new project in Azure DevOps with fresh new pipelines and check if you still have the same issue?

**Comment by Nikolara97** [comment]
Done that, everything was fresh still failing on the same policy.

**Comment by almenscorner** [comment]
I think I'm able to replicate this  now. I will run some tests tomorrow and update here!

**Comment by almenscorner** [comment]
Version 1.3.4 has been released (#94) and includes bug fixes for the Windows Enrollment profile issue where it exists with `KeyError: 'id'`.

**Comment by almenscorner** [comment]
I will keep this issue open until it is confirmed it is working for you @Nikolara97 😊

**Comment by Nikolara97** [comment]
its working now, you can close it :D 
    On Friday, February 24, 2023 at 10:46:07 AM GMT+1, Tobias Almén ***@***.***> wrote:  
 
 


I will keep this issue open until it is confirmed it is working for you @Nikolara97 😊

**Comment by almenscorner** [comment]
Fantastic, thanks for confirming :)
